### ISSUE TITLE
trace: incorrect APM metrics

### ISSUE THREAD

**Issue by arguile-** [DataDog/opencensus-go-exporter-datadog#20]
- OpenCensus uses a sampler to determine if trace should be sampled or not.
- Only sampled traces are sent to the exporters.
- Datadog trace agent gets only those sampled traces.
- That Datadog trace agent expects to get all traces for APM metrics and then do the sampling itself, so with OpenCensus these metrics will always be incomplete as sampling is done **before traces get to the Datadog trace agent**.

_A scenario to illustrate this:_

1. A probabilistic sampler with a 50% sample rate is given to the OpenCensus trace configuration.
2. Ten requests are made to the application, of which four get `true` for sampling.
3. Those four samples are sent through the exporter to the Datadog agent.
4. Within the APM view, we see only those four requests.

In this case the APM would shows four requests, no errors, and a p99 of 647µs. All hitting a single route.

_What could have happened:_

- Ten requests were made, eight to the show route and two to another other.
- Four of the requests resulted in errors.
- The p99 of the request on the main route was actually in the seconds.

There is a mismatch between how the DD APM gets its metrics (from sampled traces) and how OpenCensus collects metrics.

How much of this within the purview of this exporter I'm not certain.

(_This was also filed as a private support ticket with Datadog._)

**Comment by gbbr** [comment]
This is true. I'm afraid there isn't much we can do in this regard yet. This is a limitation of the current implementation. Perhaps it should be made more clear in a README section.

**Comment by gbbr** [comment]
@arguile- there is a possibility to fix this now, it would involve using `AlwaysSample` in OpenCensus and allowing the combination of Datadog Exporter + Agent to do the sampling instead, just like our latest integrations do it. Would that be a reasonable outcome to you?

**Comment by julianvmodesto** [comment]
Would it be possible instead use the existing OpenCensus stats rollups instead of always sampling?

**Comment by gbbr** [comment]
Since there is a solution to this problem now (https://github.com/DataDog/opencensus-go-exporter-datadog#disclaimer) I am closing this issue in favor of https://github.com/DataDog/opencensus-go-exporter-datadog/issues/31 which is related and better describes what is left to do.

For now, there is no short term solution to this except using `AlwaysSample`. We will try and keep #31 updated with progress.

@julianvmodesto you can do that but our APM product will still display wrong numbers, which is the problem discussed here.

**Comment by arguile-** [comment]
@gbbr I think the request from @julianvmodesto is the same as my initial question, that is can we not use the stats from `ochttp` for example to populate the APM metrics instead of only taking them from the traces.

I realize this could be a huge product change, but it's a reasonable approach from the point of a user.

**Comment by arguile-** [comment]
> @arguile- there is a possibility to fix this now, it would involve using `AlwaysSample` in OpenCensus and allowing the combination of Datadog Exporter + Agent to do the sampling instead, just like our latest integrations do it. Would that be a reasonable outcome to you?
> 
> Ref: #27

Yes, this seems like a reasonable work-around at this time. Thanks.

**Comment by gbbr** [comment]
This is a complicated topic that is difficult to get into depth with here without spending a lot of time, but yes you could use stats as an alternative to APM metrics, but those metrics would still be wrong in the app. APM metrics are different because of regular stats because they create computations and percentiles based on different factors and aspects of traces (such as resources, services, etc). The best way to get an understanding of how they work (if one would be interested) is to look at the "sublayer" stats in the Datadog Trace Agent's code.
