### ISSUE TITLE
trace: ochttp client and server span Name incompatible with Datadog agent

### ISSUE THREAD

**Issue by gtrevg** [DataDog/opencensus-go-exporter-datadog#35]
I've been working through some of the opencensus examples in Go and am trying leverage the [`ochttp`](https://godoc.org/go.opencensus.io/plugin/ochttp) request handler and client in order to automatically propagate span data as well as generate metrics for incoming and outgoing requests.

The issue I was seeing is that, although it looked like all the data was making it to Datadog, there was no link in the Flame Graph between the client request and the server response.  When looking at the server trace information, the interface did note the request came from my client, but it would never show the two requests together on the Flame Graph.

After much digging and turning on debug mode for the docker agent, I found several log lines similar to the following:

```
[ TRACE ] 2019-02-13 15:41:45 ERROR (api.go:249) - dropping trace reason: invalid span (SpanID:10630581837281968792): invalid `Name`: / (debug for more info), [service:"occlient" name:"/" reso...
[ TRACE ] 2019-02-13 15:41:45 ERROR (api.go:249) - dropping trace reason: invalid span (SpanID:12272109210155688068): invalid `Name`: / (debug for more info), [service:"ocserver" name:"/" reso...
```
which corresponds to [this code](https://github.com/DataDog/datadog-agent/blob/master/pkg/trace/api/api.go#L239-L250) in the agent.

It looks like by default, the `ochttp` server handler and client request code set the `Name` value to the [incoming](https://godoc.org/go.opencensus.io/plugin/ochttp#Handler) and [outgoing](https://godoc.org/go.opencensus.io/plugin/ochttp#Transport) request paths (see `FormatSpanName`).  It looks as if this `/` value for `Name` ends up invalidating the span from an Datadog API standpoint, thus breaking the trace chain.

The workaround for the server ends up being:

```go
	// Run a server
	http.HandleFunc("/", myhandler)
	log.Fatal(
		http.ListenAndServe(
			":8080",
			&ochttp.Handler{
				FormatSpanName: func(r *http.Request) string {
					path := r.URL.Path
					ddpath, _ := regexp.Compile("[^a-zA-Z0-9]+")
					path = ddpath.ReplaceAllString(path, "")
					if path == "" {
						path = "ochttp.handler"
					}
					return path
				},
			},
		),
	)

```

The workaround for the client ends up being:

```go
	client := &http.Client{
		Transport: &ochttp.Transport{
			FormatSpanName: func(r *http.Request) string {
				path := r.URL.Path
				ddpath, _ := regexp.Compile("[^a-zA-Z0-9]+")
				path = ddpath.ReplaceAllString(path, "")
				if path == "" {
					path = "ochttp.client"
				}
				return path
			},
		},
	}
        req, _ := http.NewRequest("GET", "http://127.0.0.1:8080/", nil)
        client.Do(req)
```

After adding this formatting code to both the server and client, all trace information makes it to Datadog and the Flame Graph is able to display the full trace of the client and server together.

It would seem the goal of opencensus is to implement a single means of tracing and metrics and be able to export that data to any supported exporter.  I've been able to use the server and client code without the `FormatSpanName` modification, export the data to a jaeger agent, and see the entire connected Flame Graph.

Do you think this Datadog exporter should canonicalize the `Name` value so that it's compatible with the Datadog agent?  Otherwise, it seems like developers would need to inject Datadog specific code throughout their services in order to make sure all span data makes it to the Datadog API.

Thanks,
  Trevor

**Comment by gbbr** [comment]
Hi Trevor!

Thanks a lot for the thorough description and the great workaround. This is indeed unfortunate. The main incompatibility revolves around the fact that what is called "span name" in most APM products is actually what we call "resource" in Datadog. This makes problems arise.

> Do you think this Datadog exporter should canonicalize the `Name` value so that it's compatible with the Datadog agent?

Indeed this is the only solution I can think of at the moment and perhaps is the one we should go for. At the very least accounting for the specific common use-case which is the value of `/`.

Let me consult with the team to potentially get more angles on the problem before committing to work. If you have any more suggestions please feel free to contribute them here.

**Comment by gtrevg** [comment]
@gbbr Sounds good.  Also, I did some additional testing and it seems like the restriction may be that the `Name` cannot *start* with `/`.  I have found that prefixing the value with `ochttp.handler: ` (or any other character string) fixes the issue.

```
FormatSpanName: func(r *http.Request) string {
	return "ochttp.handler: " + r.URL.Path
},
```

**Comment by gbbr** [comment]
@gtrevg I think using `FormatSpanName` is the friendliest and most customizable solution.

If we were to add this into the library, the most generic common sense one for Datadog would be prefixing it with `resource:` (imho) because we can't really tell if the spans are HTTP handlers or something else. Plus, we do use it as resource anyway. Would that be reasonable to you? In that case, you should see something like `resource:/` in the Datadog application.

**Comment by gtrevg** [comment]
Yes, that solution would work.

I think the main goal would to be to keep it from silently failing.  From the application standpoint, there are no errors produced.  One would have to go to wherever the agent is deployed and dig through logs on that server in order to find out some of the application spans aren't being transmitted.

Thanks!

**Comment by gbbr** [comment]
Before doing that, I'm going to investigate changing the trace agent to allow slashes in the span name, as that might be a better solution. If that won't work as a short term solution, we can go back to the suggested one with the prefix.

**Comment by gbbr** [comment]
Having looked into it, the above is not an option at the moment due to other implications in our pipeline. So I guess we'll have to go with the prefix. Happy to commit at some point (not sure when) and also happy to receive contributions if you care to do so.

I would suggest to prefix _all_ span names with `resource:`, without running a Regex or any checks (to avoid slowing things down), because this will always be semantically accurate wrt Datadog (what we call resource is the name of the span in Opencensus).

**Comment by gbbr** [comment]
Unfortunately changing this in our system (to allow slashes in names) runs much deeper and can't be done easily due to various reasons. I've opened an initial PR for review, as a suggestion to work with this issue.

**Comment by gbbr** [comment]
I'd be curious if you could try it out and share your opinion on it. As context, in Datadog it's required for a service to have consistent (the same) top-level name for the same code path in order to get good results from instrumentation, most specifically around APM stats. This change would help with that.

**Comment by lwc** [comment]
FWIW we ran into a few issues when attempting to use the vanilla ochttp stuff with datadog and ended up with a `trace.Exporter` decorator for datadog that looks something like this:

```go 
const ddOperationTypeAttr = "datadog.operation.type"

//ExportSpan massages an OpenCensus trace span for consumption by DataDog
func (d ddNormalisingExporter) ExportSpan(s *trace.SpanData) {
	dd := copySpanData(s)

	if ddName, ok := dd.Attributes[ddOperationTypeAttr].(string); ok {
		dd.Name = ddName // Datadog uses the span name for aggregation

		// span.type is a datadog span classifier, set it for known span types
		switch ddName {
		case "web.server.request":
			dd.Attributes["span.type"] = "web"
		case "web.client.request":
			dd.Attributes["span.type"] = "http"
		}
	}

	// Datadog uses an attr "resource.name" for what OC calls the span name
	dd.Attributes["resource.name"] = s.Name

	// Datadog wants http status code to be a string, ints aren't processed correctly
	if status, ok := dd.Attributes["http.status_code"].(int64); ok {
		dd.Attributes["http.status_code"] = strconv.Itoa(int(status))
	}

	delete(dd.Attributes, ddOperationTypeAttr)
	// Send the tweaked span to DataDog
	d.Exporter.ExportSpan(dd)
}
```

This gets us proper integration with DataDog's features, while keeping the apps able to have a fairly vanilla OpenCensus integration.

**Comment by gbbr** [comment]
@lwc thanks for sharing that. What you did is correct and I'm glad it works for you. I'm open to ideas about how we could improve our exporter to make this easier. It's hard to make assumptions like this on the grand scale because you don't know what users are using (ochttp or something else).

The PR I've linked to is not _the_ solution but it should still provide a better "out of the box" outcome than what we had before. I'd be curious to hear feedback on it or additional ideas.

**Comment by gtrevg** [comment]
@gbbr I'll try out the pull request today to see how it plays out. thanks

**Comment by gbbr** [comment]
@gtrevg did you have any luck trying this out or were you already happy enough with your `FormatSpanName` solution and stuck with that? Your solution is still superior to us naming all spans `opencensus`.

**Comment by lwc** [comment]
FWIW https://github.com/DataDog/opencensus-go-exporter-datadog/pull/36 broke the solution I posted in this thread :(

**Comment by gbbr** [comment]
I guess since the original problem is now solved, and broken traces are no longer reported, it's fine to close this.

@lwc I'm happy to work together to solve any new issues you may be encountering and potentially discuss the change in #36. If you're open to doing that, please open a separate issue describing the problem, perhaps others can benefit too.
